//
//  BigFormRouter.swift
//  BigForm
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-11 07:55:30 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol BigFormRouterInput {

}

// MARK: Implementation

class BigFormRouter: BigFormRouterInput {

}
