//
//  BigFormBuilder.swift
//  BigForm
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-11 07:55:30 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct BigFormBuilder {

	func assembleModule() -> BigFormViewController {
		let viewController = BigFormViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> BigFormViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! BigFormViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: BigFormViewController) {

		let router = BigFormRouter()

		let presenter = BigFormPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = BigFormInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
