//
//  CategoryPickerRouter.swift
//  CategoryPicker
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-24 12:15:36 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol CategoryPickerRouterInput {
	func presentMainTabbar()
}

// MARK: Implementation

class CategoryPickerRouter: CategoryPickerRouterInput {
	func presentMainTabbar() {
		guard let keyWindow = UIApplication.shared.keyWindow else { return }
		
		UIView.transition(
			with: keyWindow,
			duration: 0.2,
			options: .transitionFlipFromLeft,
			animations: {
				keyWindow.rootViewController = MainTabBarViewController()
			},
			completion: { _ in
				AppSettings.isUserIntroducedToApp = true
			}
		)
		
	}
}
