//
//  CategoryPickerInteractor.swift
//  CategoryPicker
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-24 12:15:36 +0000 lobster.kz. All rights reserved.
//

protocol CategoryPickerInteractorInput {

}

// MARK: Implementation

class CategoryPickerInteractor: CategoryPickerInteractorInput {

	weak var output: CategoryPickerInteractorOutput!

}
		