//
//  CategoryPickerRouter.swift
//  CategoryPicker
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-24 12:15:36 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol CategoryPickerRouterInput {

}

// MARK: Implementation

class CategoryPickerRouter: CategoryPickerRouterInput {

}
