//
//  CategoryPickerViewController.swift
//  CategoryPicker
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-24 12:15:36 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol CategoryPickerViewInput: class {
	func setupInitialState()
}

extension CategoryPickerViewController: CategoryPickerViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		configureTableViewStyle()
		configureTableViewLayout()
		configureTableViewDataSource()
	}

}


class CategoryPickerViewController: UIViewController {

	// MARK: Properties
	var output: CategoryPickerViewOutput!
	private var tableView: UITableView!
	private var dataSource: TableViewDataSource<Int, UITableViewCell>!

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}

	
	// MARK: Private methods
	
	private func configureTableViewStyle() {
		let tableView = UITableView(frame: .zero, style: .grouped)
		tableView.tableFooterView = UIView()
		self.tableView = tableView
	}
	
	private func configureTableViewLayout() {
		view.addSubview(tableView)
		tableView.addConstraintsProgrammatically
			.pinToSuperSafeArea()
	}
	
	private func configureTableViewDataSource() {
		dataSource = TableViewDataSource(tableView){ (p: Int,c: UITableViewCell) in
			c.textLabel?.text = "\(p)"
		}
		
		tableView.dataSource = dataSource
	}
	
}


