//
//  LanguageChoicePresenter.swift
//  LanguageChoice
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-07 14:08:05 +0000 lobster.kz. All rights reserved.
//
		
import SharedCodeFramework

class LanguageChoicePresenter: LanguageChoiceModuleInput {
	
	weak var view: LanguageChoiceViewInput!
	var interactor: LanguageChoiceInteractorInput!
	var router: LanguageChoiceRouterInput!

}


// MARK: ViewController output protocol

protocol LanguageChoiceViewOutput {
	func viewIsReady()
}

extension LanguageChoicePresenter: LanguageChoiceViewOutput {
	func viewIsReady() {
		view.setupInitialState()
		view.setupView(with:
			LanguageChoiceView.Props(
				chooseKazakh: Command{
					self.router.presentGreeting()
				},
				chooseRus: Command{
					self.router.presentGreeting()
			})
		)
		
	}

}


// MARK: Interactor output protocol

protocol LanguageChoiceInteractorOutput: class {

}

extension LanguageChoicePresenter: LanguageChoiceInteractorOutput {

}

