//
//  LanguageChoiceRouter.swift
//  LanguageChoice
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-07 14:08:05 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol LanguageChoiceRouterInput {
	func presentGreeting()
}

// MARK: Implementation

class LanguageChoiceRouter: LanguageChoiceRouterInput {
	
	var viewController: UIViewController?
	
	func presentGreeting() {
		viewController?.navigationController?.pushViewController(
			GreetingModuleConfigurator().assembleModule(), animated: true
		)
	}

}
