//
//  MapPresenter.swift
//  Map
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-23 16:55:07 +0000 lobster.kz. All rights reserved.
//
		
class MapPresenter: MapModuleInput {
	
	weak var view: MapViewInput!
	var interactor: MapInteractorInput!
	var router: MapRouterInput!

}


// MARK: ViewController output protocol

protocol MapViewOutput {
	func viewIsReady()
}

extension MapPresenter: MapViewOutput {
	func viewIsReady() {
		view.setupInitialState()
	}

}


// MARK: Interactor output protocol

protocol MapInteractorOutput: class {

}

extension MapPresenter: MapInteractorOutput {

}

