//
//  MapRouter.swift
//  Map
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-23 16:55:07 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol MapRouterInput {

}

// MARK: Implementation

class MapRouter: MapRouterInput {

}
