//
//  UpdateProfilePresenter.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//
		
class UpdateProfilePresenter {
	
	weak var view: UpdateProfileViewInput!
	var interactor: UpdateProfileInteractorInput!
	var router: UpdateProfileRouterInput!

}

// MARK: ViewController output protocol

protocol UpdateProfileViewOutput {
	func viewIsReady()
}

extension UpdateProfilePresenter: UpdateProfileViewOutput {
	func viewIsReady() {
		view.setupInitialState()
	}

}

// MARK: Interactor output protocol

protocol UpdateProfileInteractorOutput: class {

}

extension UpdateProfilePresenter: UpdateProfileInteractorOutput {

}
