//
//  UpdateProfileInteractor.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//

protocol UpdateProfileInteractorInput {

}

// MARK: Implementation

class UpdateProfileInteractor: UpdateProfileInteractorInput {

	weak var output: UpdateProfileInteractorOutput!

}
		