//
//  UpdateProfileInteractor.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//

protocol UpdateProfileInteractorInput {
	func edit(_ profile: PutProfile)
}

// MARK: Implementation

class UpdateProfileInteractor: UpdateProfileInteractorInput {

	weak var output: UpdateProfileInteractorOutput!
	
	func edit(_ profile: PutProfile) {
		let onSuccess = { [weak self] (empty: Empty) -> Void in
			self?.output.didSucceedUpdate()
		}
		
		let onFailure = { [weak self] (error: Error) -> Void in
			self?.output.didFailUpdate(with: error)
		}
		
		APIUpdateProfile(onSuccess: onSuccess, onFailure: onFailure, profile: profile)
			.dispatch()
	}

}
		
