//
//  UpdateProfileRouter.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol UpdateProfileRouterInput {

}

// MARK: Implementation

class UpdateProfileRouter: UpdateProfileRouterInput {

}


//MARK: - Assemble module

extension UpdateProfileViewController {
	
	static var module: UpdateProfileViewController {
		let viewController = UpdateProfileViewController()
		configure(viewController: viewController)
		return viewController
	}
	
	static private func configure(viewController: UpdateProfileViewController) {
		let router = UpdateProfileRouter()
		let presenter = UpdateProfilePresenter()
		presenter.view = viewController
		presenter.router = router
		let interactor = UpdateProfileInteractor()
		interactor.output = presenter
		presenter.interactor = interactor
		viewController.output = presenter
	}
	
}
