//
//  FilterRouter.swift
//  Filter
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-03 14:19:21 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol FilterRouterInput {
	func presentPicker(with vc: UIViewController, category: Category)
}

// MARK: Implementation

class FilterRouter: FilterRouterInput {
	func presentPicker(with vc: UIViewController, category: Category) {
		let picker = ObjectCategoryPickerViewController()
		picker.category = category
		vc.navigationController?.pushViewController(picker, animated: true)
	}
}
