//
//  FilterInteractor.swift
//  Filter
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-03 14:19:21 +0000 lobster.kz. All rights reserved.
//

protocol FilterInteractorInput {

}

// MARK: Implementation

class FilterInteractor: FilterInteractorInput {

	weak var output: FilterInteractorOutput!

}
		