//
//  FilterInteractor.swift
//  Filter
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-03 14:19:21 +0000 lobster.kz. All rights reserved.
//

protocol FilterInteractorInput {
	func loadCategories()
}

// MARK: Implementation

class FilterInteractor: FilterInteractorInput {

	weak var output: FilterInteractorOutput!
	
	func loadCategories() {
		if let storedCats = CategoriesStorage.shared.retrieveData() {
			output.didLoad(storedCats)
		}
		
		let onSuccess = { [weak self] (categories: [Category]) -> Void in
			self?.output.didLoad(categories)
			CategoriesStorage.shared.store(categories)
		}
		
		let onFailure = { [weak self] (error: Error) -> Void in
			self?.output.didFailLoadCategories(with: error)
		}
		
		APICategories(onSuccess: onSuccess, onFailure: onFailure).dispatch()
		
	}

}
		