//
//  VenueViewController.swift
//  Venue
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-26 12:44:17 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol VenueViewInput where Self: UIViewController {
	func setupInitialState()
	func setup(venueProps: UIVenueView.VenueProps)
}

extension VenueViewController: VenueViewInput {

	func setupInitialState() {
		view.backgroundColor = .clear
		view.addSubview(rootView)
		rootView.addConstraintsProgrammatically
			.pinToSuper()
	}
	
	func setup(venueProps: UIVenueView.VenueProps) {
		rootView.props = venueProps
	}

}

class VenueViewController: UIViewController {

	var output: VenueViewOutput!
	var rootView = UIVenueView()

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}

}
