//
//  UpdateProfileViewController.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol UpdateProfileViewInput where Self: UIViewController {
	func setupInitialState()
}

class UpdateProfileViewController: TableViewController, UpdateProfileViewInput {

	var output: UpdateProfileViewOutput!

	func setupInitialState() {
		navigationItem.title = l10n(.editing)
		configureTableview()
	}
	
	private func configureTableview() {
		
	}
	

}

extension UpdateProfileViewController {

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		view.backgroundColor = .white
		output.viewIsReady()
	}

}
