//
//  UpdateProfileViewController.swift
//  UpdateProfile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-09 12:10:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol UpdateProfileViewInput where Self: UIViewController {
	func setupInitialState()
	func updateTable(with configurators: [CellConfiguratorType])
	func reloadData()
}

class UpdateProfileViewController: TableViewController, UpdateProfileViewInput {

	var output: UpdateProfileViewOutput!
	
	private var dataSource: FormTableViewDataSource!

	func setupInitialState() {
		navigationItem.title = l10n(.editing)
		navigationItem.rightBarButtonItem = UIBarButtonItem(
			title: l10n(.close), style: .done,
			target: self,
			action: #selector(close)
		)
		configureTableview()
	}
	
	private func configureTableview() {
		tableView.register(cellClass: TextCell.self)
		tableView.register(cellClass: TextFormCell.self)
		dataSource = FormTableViewDataSource("")
		tableView.dataSource = dataSource
	}
	
	func updateTable(with configurators: [CellConfiguratorType]) {
		dataSource.configurators = configurators
	}
	
	func reloadData() {
		tableView.reloadData()
	}
	
	@objc func close() {
		dismiss(animated: true, completion: nil)
	}

}

extension UpdateProfileViewController {

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		view.backgroundColor = .white
		output.viewIsReady()
	}

}
