//
//  BlogViewController.swift
//  Blog
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-14 10:27:15 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol BlogViewInput where Self: UIViewController {
	func setupInitialState()
}

extension BlogViewController: BlogViewInput {

	func setupInitialState() {
	
	}

}

class BlogViewController: UIViewController {

	var output: BlogViewOutput!

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		view.backgroundColor = .white
		output.viewIsReady()
	}

}
