//
//  SearchResultsViewControllerRouter.swift
//  SearchResultsViewController
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-03-01 13:52:49 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol SearchResultsViewControllerRouterInput {

}

// MARK: Implementation

class SearchResultsViewControllerRouter: SearchResultsViewControllerRouterInput {

}
