//
//  SearchResultsViewControllerPresenter.swift
//  SearchResultsViewController
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-03-01 13:52:49 +0000 lobster.kz. All rights reserved.
//
import SharedCodeFramework
		
class SearchResultsViewControllerPresenter: SearchResultsViewControllerModuleInput {
	
	weak var view: SearchResultsViewControllerViewInput!
	var interactor: SearchResultsViewControllerInteractorInput!
	var router: SearchResultsViewControllerRouterInput!

	var didPressShowOnMap: Command = .nop
}


// MARK: ViewController output protocol

protocol SearchResultsViewControllerViewOutput {
	func viewIsReady()
	func initView(with command: Command)
}

extension SearchResultsViewControllerPresenter: SearchResultsViewControllerViewOutput {
	
	func initView(with command: Command) {
		self.didPressShowOnMap = command
	}
	
	func viewIsReady() {
		view.setupInitialState()
		didPressShowOnMap.perform()
	}

}


// MARK: Interactor output protocol

protocol SearchResultsViewControllerInteractorOutput: class {
	
}

extension SearchResultsViewControllerPresenter: SearchResultsViewControllerInteractorOutput {

}

