//
//  FilterViewController.swift
//  Filter
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-03 14:19:21 +0000 lobster.kz. All rights reserved.
//

import SharedCodeFramework

// MARK: View input protocol

protocol FilterViewInput where Self: UIViewController {
	func setupInitialState()
	func makeForm(with filter: Filter)
	func updateForm(with filter: Filter)
	
	var onRightButtonTouch: CommandWith<OverallScore> { get set }
	var onSelectCategory: CommandWith<Category> { get set }
}

extension FilterViewController: FilterViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		navigationItem.title = l10n(.filter)
		let backItem = UIBarButtonItem()
		backItem.title = l10n(.done)
		navigationItem.backBarButtonItem = backItem
		navigationItem.rightBarButtonItem = UIBarButtonItem(
			barButtonSystemItem: .cancel,
			target: self,
			action: #selector(closeFilterForm)
		)
		configureTableView()
		configureButton()
	}
		
	func updateForm(with filter: Filter) {
		self.filter = filter
		updateFirstSectionData()
		updateSecondSectionData()
	}
	
	func makeForm(with filter: Filter) {
		self.filter = filter
		updateFirstSectionData()
		updateSecondSectionData()
	}
	
	@objc func closeFilterForm() {
		dismiss(animated: true, completion: nil)
	}

}

class FilterViewController: UIViewController {

	var output: FilterViewOutput!
	let tableView = UITableView(frame: .zero, style: .plain)
	let clearFilter = Button(type: .system)
	var onRightButtonTouch: CommandWith<OverallScore> = .nop
	var onSelectCategory: CommandWith<Category> = .nop
	
	var filter = Filter() {
		didSet {
			print("Filter has been set")
		}
	}

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}
	
	// MARK: - Private fields
	
	var sectionOneDataSource: TableViewDataSource<BasicCell.Props, BasicCell>!
	var sectionTwoDataSource: TableViewDataSource<BasicCell.Props, BasicCell>!
	var tableViewDataSource: SectionedTableViewDataSource!
	
	private func configureTableView() {
		tableView.tableFooterView = UIView()
		
		/// Data sources
		sectionOneDataSource = TableViewDataSource(tableView, l10n(.objectAccessibility).uppercased()) { $1.props = $0 }
		sectionTwoDataSource = TableViewDataSource(tableView, l10n(.objectCategories).uppercased()) { $1.props = $0 }
		tableViewDataSource  = SectionedTableViewDataSource(dataSources: [sectionOneDataSource, sectionTwoDataSource])
		tableView.dataSource = tableViewDataSource
		
		/// Header views for sections
		tableView.delegate = self
		
		/// Table view layout
		view.addSubview(tableView)
		
		view.addSubview(clearFilter)
		
		tableView.translatesAutoresizingMaskIntoConstraints = false
		clearFilter.translatesAutoresizingMaskIntoConstraints = false
		
		let tc = [
			tableView.leadingAnchor.constraint(equalTo: view.safeLayoutGuide.leadingAnchor),
			tableView.topAnchor.constraint(equalTo: view.safeLayoutGuide.topAnchor),
			tableView.trailingAnchor.constraint(equalTo: view.safeLayoutGuide.trailingAnchor),
		]
		
		let bc = [
			clearFilter.topAnchor.constraint(equalTo: tableView.bottomAnchor, constant: 0),
			clearFilter.leadingAnchor.constraint(equalTo: view.safeLayoutGuide.leadingAnchor),
			clearFilter.trailingAnchor.constraint(equalTo: view.safeLayoutGuide.trailingAnchor),
			clearFilter.bottomAnchor.constraint(equalTo: view.safeLayoutGuide.bottomAnchor),
			clearFilter.heightAnchor.constraint(equalToConstant: 56)
		]
		
		NSLayoutConstraint.activate(tc + bc)
		
	}
	
	private func configureButton() {
		clearFilter.decorate(with:
			Style.systemFont(size: 14),
			Style.titleColor(color: .white),
			Style.backgroundColor(color: UIColor.init(named: "SelectedTabbarTintColor"))
		)
		
		clearFilter.setTitle(l10n(.clearAll), for: .normal)
	}

	private func updateFirstSectionData() {
		
		let cellOne = BasicCell.Props(
			text: l10n(.accessibleFull),
			icon: Asset.local("available_32"),
			rightIcon: filter.icon(.fullAccessible),
			onRightButtonTouch: CommandWith {
				self.onRightButtonTouch.perform(with: .fullAccessible)
			}
		)
		let cellTwo = BasicCell.Props(
			text: l10n(.accessiblePartial),
			icon: Asset.local("partially_available_32"),
			rightIcon: filter.icon(.partialAccessible),
			onRightButtonTouch: CommandWith {
				self.onRightButtonTouch.perform(with: .partialAccessible)
			}
		)
		
		let cellThree = BasicCell.Props(
			text: l10n(.accessibleNone),
			icon: Asset.local("not_available_32"),
			rightIcon: filter.icon(.notAccessible),
			onRightButtonTouch: CommandWith {
				self.onRightButtonTouch.perform(with: .notAccessible)
			}
		)
		
		sectionOneDataSource.cellsProps = [cellOne, cellTwo, cellThree]
		tableView.reloadData()
	}
	
	private func updateSecondSectionData() {
		let cells = filter.cat.map { categ in
			return BasicCell.Props(
				text: categ.title,
				icon: Asset.fontAwesome(categ.icon),
				rightIcon: "chevron_right_passive",
				onRightButtonTouch: CommandWith {
					self.onSelectCategory.perform(with: categ)
				}
			)
		}
		
		sectionTwoDataSource.cellsProps = cells
		tableView.reloadData()
	}
	
}

extension FilterViewController: UITableViewDelegate {
	func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
		let cell = UITableViewCell()
		cell.backgroundColor = UIColor(named:"FilterHeaderColor")
		cell.textLabel?.textColor = UIColor(named: "FilterHeaderTextColor")
		cell.textLabel?.font = .systemFont(ofSize: 13)
		cell.textLabel?.text = tableViewDataSource.titles[section]
		return cell
	}
	
}
