//
//  ComplaintBuilder.swift
//  Complaint
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-21 07:01:46 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct ComplaintBuilder {

	func assembleModule() -> ComplaintViewController {
		let viewController = ComplaintViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> ComplaintViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! ComplaintViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: ComplaintViewController) {

		let router = ComplaintRouter()

		let presenter = ComplaintPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = ComplaintInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
