//
//  ComplaintRouter.swift
//  Complaint
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-21 07:01:46 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol ComplaintRouterInput {

}

// MARK: Implementation

class ComplaintRouter: ComplaintRouterInput {

}
