//
//  VenueDescriptionViewController.swift
//  VenueDescription
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-27 16:23:49 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol VenueDescriptionViewInput where Self: UIViewController {
	func setupInitialState()
}

extension VenueDescriptionViewController: VenueDescriptionViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		view.addSubview(rootView)
		rootView.addConstraintsProgrammatically.pinToSuper()
	}

}

class VenueDescriptionViewController: UIViewController {

	var output: VenueDescriptionViewOutput!
	var rootView = VenueDescriptionView()

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}

}
