//
//  AuthBuilder.swift
//  Auth
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-17 07:43:27 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct AuthBuilder {

	func assembleModule() -> AuthViewController {
		let viewController = AuthViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> AuthViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! AuthViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: AuthViewController) {

		let router = AuthRouter()

		let presenter = AuthPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = AuthInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
