//
//  AuthPresenter.swift
//  Auth
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-17 07:43:27 +0000 lobster.kz. All rights reserved.
//
import SharedCodeFramework

protocol AuthViewOutput {
	func viewIsReady()
}
		
class AuthPresenter: AuthViewOutput {
	
	weak var view: AuthViewInput!
	var interactor: AuthInteractorInput!
	var router: AuthRouterInput!

	func viewIsReady() {
		view.setupInitialState()
		view.onTouchNext = Command { [weak self] in
			self?.view.viewPage = .second
		}
	}
	
}


// MARK: Interactor output protocol

protocol AuthInteractorOutput: class {

}

extension AuthPresenter: AuthInteractorOutput {

}
