//
//  AuthRouter.swift
//  Auth
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-17 07:43:27 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol AuthRouterInput {
	func showProfile(for vc: UIViewController)
}

// MARK: Implementation

class AuthRouter: AuthRouterInput {
	func showProfile(for vc: UIViewController) {
		let profile = ProfileBuilder().assembleTab()
		vc.tabBarController?.viewControllers![3] = profile
	}
}
