//
//  ProfileViewController.swift
//  Profile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-18 08:16:13 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol ProfileViewInput where Self: UIViewController {
	func setupInitialState()
	var profileView: ProfileView { get }
	func showActionSheet(with actions: [Action])
}

extension ProfileViewController: ProfileViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		navigationItem.title = l10n(.myProfile)
		configureViews(with: profileView)
	}
	
	func showActionSheet(with actions: [Action]) {
		let sheet = GenericAlertPresenter(
			title: l10n(.avatarChoice),
			style: .actionSheet,
			actions: actions
		)
		sheet.present(in: self)
	}
	
}

class ProfileViewController: ProfileDrawerViewController {

	var output: ProfileViewOutput!
	let profileView = ProfileView()

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		output.viewWillAppear()
	}

}
