//
//  BlogsViewController.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol BlogsViewInput where Self: UIViewController {
	func setupInitialState()
	func updateTable(with items: [Item])
}

extension BlogsViewController: BlogsViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		dataSource = UTableViewDataSource<BlogCell>(tableView)
		tableView.dataSource = dataSource
	}
	
	func updateTable(with items: [Item]) {
		let cellsProps = items.map { BlogCell.Props(title: $0.title) }
		dataSource.cellsProps = cellsProps
		tableView.reloadData()
	}

}

class BlogsViewController: TableViewController {

	var output: BlogsViewOutput!
	var dataSource: UTableViewDataSource<BlogCell>!

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}

}
