//
//  LanguageChoiceModuleIO.swift
//  LanguageChoice
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-07 14:08:05 +0000 lobster.kz. All rights reserved.
//

protocol LanguageChoiceModuleInput: class {
	
}

protocol LanguageChoiceModuleOutput: class {
	
}
