# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Upload adhoc version to diawi and send the link to email"
  lane :beta do
    gym(scheme: "DosKaz", export_method: "ad-hoc", output_directory: "../build", configuration: "Debug")
    # diawi(token: "l4VvYe6lBNgZUyAG0R3BTgGMGHXrjF6OdVXEJ9CYEO", callback_emails:"ykulanbekov@nu.edu.kz")
    diawi(token: "l4VvYe6lBNgZUyAG0R3BTgGMGHXrjF6OdVXEJ9CYEO")
  end

  desc "Adhoc build"
  lane :adhoc do
    gym(scheme: "DosKaz", export_method: "ad-hoc", output_directory: "../build", configuration: "Debug")
  end
end
