//
//  GreetingModuleIO.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//

protocol GreetingModuleInput: class {
	
}

protocol GreetingModuleOutput: class {
	
}
