//
//  SearchResultsViewControllerModuleIO.swift
//  SearchResultsViewController
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-03-01 13:52:49 +0000 lobster.kz. All rights reserved.
//

protocol SearchResultsViewControllerModuleInput: class {
	
}

protocol SearchResultsViewControllerModuleOutput: class {
	func didPressShowOnMap()
}
