//
//  SearchResultsViewControllerConfigurator.swift
//  SearchResultsViewController
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-03-01 13:52:49 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct SearchResultsViewControllerModuleConfigurator {

	func assembleModule() -> SearchResultsViewControllerViewController {
		let viewController = SearchResultsViewControllerViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> SearchResultsViewControllerViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! SearchResultsViewControllerViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: SearchResultsViewControllerViewController) {

		let router = SearchResultsViewControllerRouter()

		let presenter = SearchResultsViewControllerPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = SearchResultsViewControllerInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
