//
//  BlogsRouter.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol BlogsRouterInput {
	func showBlog(with vc: UIViewController, blog: Item)
}

// MARK: Implementation

class BlogsRouter: BlogsRouterInput {
	func showBlog(with vc: UIViewController, blog: Item) {
		let blogVC = BlogBuilder().assembleModule()
		blogVC.output.initView(with: blog)
		vc.navigationController?.pushViewController(blogVC, animated: true)
	}
	
}
