//
//  BlogsBuilder.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct BlogsBuilder {
	
	func assembleTab() -> UIViewController {
		return assembleModule().tab(with: "blog", title: l10n(.blog))
	}

	func assembleModule() -> BlogsViewController {
		let viewController = BlogsViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> BlogsViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! BlogsViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: BlogsViewController) {

		let router = BlogsRouter()

		let presenter = BlogsPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = BlogsInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
