//
//  BlogsRouter.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol BlogsRouterInput {

}

// MARK: Implementation

class BlogsRouter: BlogsRouterInput {

}
