//
//  BlogsPresenter.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//
		
class BlogsPresenter {
	
	weak var view: BlogsViewInput!
	var interactor: BlogsInteractorInput!
	var router: BlogsRouterInput!

}

// MARK: ViewController output protocol

protocol BlogsViewOutput {
	func viewIsReady()
}

extension BlogsPresenter: BlogsViewOutput {
	func viewIsReady() {
		view.setupInitialState()
	}

}

// MARK: Interactor output protocol

protocol BlogsInteractorOutput: class {

}

extension BlogsPresenter: BlogsInteractorOutput {

}
