//
//  BlogsInteractor.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

protocol BlogsInteractorInput {

}

// MARK: Implementation

class BlogsInteractor: BlogsInteractorInput {

	weak var output: BlogsInteractorOutput!

}
		