//
//  BlogsInteractor.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//
import  SharedCodeFramework

protocol BlogsInteractorInput {
	func loadPosts(with searchText: String?, categoryId: Int?)
	func resetPaginator() -> Void
	func loadBlogCategories()
	func searchPosts(with searchText: String?, categoryId: Int?)
}

// MARK: Implementation

class BlogsInteractor: BlogsInteractorInput {

	weak var output: BlogsInteractorOutput!
	
	let paginator = BlogPaginator()
	
	func searchPosts(with searchText: String?, categoryId: Int?) {
		let onSuccess = { [weak self] (blogResponse: BlogResponse) -> Void in
			self?.output.didLoadSearch(blogResponse)
		}

		let onFailure = { [weak self] (error: Error) -> Void in
			self?.output.didFailLoadBlogResponse(with: error)
		}

		let request = APIBlogPosts(
			onSuccess: onSuccess,
			onFailure: onFailure,
			page: 1,
			search: searchText,
			categoryId: categoryId
		)

		request.dispatch()
	}

	func resetPaginator() -> Void {
		paginator.reset()
	}
	
	func loadPosts(with searchText: String?, categoryId: Int?) {
		paginator.search = searchText
		paginator.categoryId = categoryId
		paginator.onLoad = CommandWith<BlogResponse> { [weak self] blogResponse in
			self?.output.didload(blogResponse)
		}
		paginator.onFail = CommandWith<Error> { [weak self] error in
			self?.output.didFailLoadBlogResponse(with: error)
		}
		paginator.loadNext()
	}
	
	func loadBlogCategories() {
		APIBlogCategories(onSuccess: { [weak self] (blogCategories) in
			let all = BlogCategory(id: nil, title: l10n(.all))
			var copy = blogCategories
			copy.insert(all, at: 0)
			self?.output?.didLoad(copy)
		}, onFailure: { error in
			print(error)
		})
		.dispatch()
	}

}
		
