//
//  BlogsInteractor.swift
//  Blogs
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-14 17:21:04 +0000 lobster.kz. All rights reserved.
//

protocol BlogsInteractorInput {
	func loadPosts(with searchText: String?, categoryId: Int?)
	func loadBlogCategories()
}

// MARK: Implementation

class BlogsInteractor: BlogsInteractorInput {

	weak var output: BlogsInteractorOutput!
	
	func loadPosts(with searchText: String?, categoryId: Int?) {
		let onSuccess = { [weak self] (blogResponse: BlogResponse) -> Void in
			self?.output.didload(blogResponse)
		}
		
		let onFailure = { [weak self] (error: Error) -> Void in
			self?.output.didFailLoadBlogResponse(with: error)
		}
		
		let r = APIBlogPosts(
			onSuccess: onSuccess,
			onFailure: onFailure,
			page: 1,
			search: searchText,
			categoryId: categoryId
		)
		
		r.dispatch()
	}
	
	func loadBlogCategories() {
		APIBlogCategories(onSuccess: { [weak self] (blogCategories) in
			self?.output?.didLoad(blogCategories)
		}, onFailure: { error in
			print(error)
		})
		.dispatch()
	}

}
		
