//
//  LanguageChoiceViewController.swift
//  LanguageChoice
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-07 14:08:05 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol LanguageChoiceViewInput: class {
	func setupInitialState()
}

extension LanguageChoiceViewController: LanguageChoiceViewInput {

	func setupInitialState() {
	
	}

}


class LanguageChoiceViewController: UIViewController {

	var output: LanguageChoiceViewOutput!

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		view.backgroundColor = .white
		output.viewIsReady()
	}

}

