//
//  VenueInteractor.swift
//  Venue
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-26 12:44:17 +0000 lobster.kz. All rights reserved.
//

protocol VenueInteractorInput {

}

// MARK: Implementation

class VenueInteractor: VenueInteractorInput {

	weak var output: VenueInteractorOutput!

}
		