//
//  VenueRouter.swift
//  Venue
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-26 12:44:17 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol VenueRouterInput {

}

// MARK: Implementation

class VenueRouter: VenueRouterInput {

}
