//
//  MapViewController.swift
//  Map
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-23 16:55:07 +0000 lobster.kz. All rights reserved.
//

import UIKit
import MapKit
import SharedCodeFramework

// MARK: View input protocol

protocol MapViewInput: class {
	func setupInitialState()
	func buildSearch(with command: Command)
	func show(_ points: [Venue])
	func showSheet(for doskazVenue: DoskazVenue)
	
	var onSelectVenue: CommandWith<Int> { get set }
}

extension MapViewController: MapViewInput {

	func setupInitialState() {
		configureMapViewLayout()
		configureMapView()
		configureNavigationView()
		addDrawerViewController()
	}

	func show(_ points: [Venue]) {
		mapView.addAnnotations(points)
	}
	
	func showSheet(for doskazVenue: DoskazVenue) {
		drawerVC.setPositionToHalf()
	}
}


class MapViewController: UIViewController {

	// MARK: Properties
	var output: MapViewOutput!
	private var mapView: MKMapView!
	private let regionRadius: CLLocationDistance = 5000
	private var searchController: UISearchController!
	
	var onSelectVenue: CommandWith<Int> = .nop

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		view.backgroundColor = .white
		output.viewIsReady()
	}
	
	let drawerVC = DrawerViewController()
		
	func addDrawerViewController() {
		addChild(drawerVC)
		view.addSubview(drawerVC.drawerView)
		drawerVC.didMove(toParent: self)
		
		drawerVC.drawerView.addConstraintsProgrammatically
			.pinToSuper()
	}

	private func configureMapViewLayout() {
		let mapView = MKMapView()
		view.addSubview(mapView)
		mapView.addConstraintsProgrammatically
			.pinToSuperSafeArea()
		self.mapView = mapView
	}
	
	private func configureMapView() {
		// set initial location
		let baiterek = (lat: 52.288218, lon: 76.969872)
		let initialLocation = CLLocation(latitude: baiterek.lat, longitude: baiterek.lon)
		centerMapOnLocation(location: initialLocation)
		
		mapView.delegate = self
		mapView.register(VenueView.self, forAnnotationViewWithReuseIdentifier: MKMapViewDefaultAnnotationViewReuseIdentifier)
		
	}
	
	private func configureNavigationView() {
		navigationItem.rightBarButtonItem = UIBarButtonItem(
			image: UIImage(named: "filter")?.withRenderingMode(.alwaysOriginal),
			style: .plain,
			target: nil,
			action: nil
		)
	}
	
	func buildSearch(with command: Command) {
		let resultsController = SearchResultsViewControllerModuleConfigurator().assembleModule()
		resultsController.output.initView(with: command)
		let searchController = UISearchController(searchResultsController: resultsController)
		searchController.searchResultsUpdater = resultsController
		searchController.hidesNavigationBarDuringPresentation = false
		
		definesPresentationContext = true
		navigationItem.titleView = searchController.searchBar
		self.searchController = searchController
		searchController.searchBar.customize()
	}
	
	// MARK: - Helper methods
	
	private func centerMapOnLocation(location: CLLocation) {
		let coordinateRegion = MKCoordinateRegion(
			center: location.coordinate,
			latitudinalMeters: regionRadius,
			longitudinalMeters: regionRadius
		)
		mapView.setRegion(coordinateRegion, animated: true)
	}
	
}


// MARK: - MKMapViewDelegate

extension MapViewController: MKMapViewDelegate {
	func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView) {
		let location = view.annotation as! Venue
		print(location.coordinate)
		mapView.deselectAnnotation(view.annotation, animated: false)
		onSelectVenue.perform(with: location.id)
	}
}

