//
//  MapModuleIO.swift
//  Map
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-02-23 16:55:07 +0000 lobster.kz. All rights reserved.
//

protocol MapModuleInput: class {
	
}

protocol MapModuleOutput: class {
	
}
