//
//  ProfilePresenter.swift
//  Profile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-18 08:16:13 +0000 lobster.kz. All rights reserved.
//

import SharedCodeFramework
		
class ProfilePresenter {
	
	weak var view: ProfileViewInput!
	var interactor: ProfileInteractorInput!
	var router: ProfileRouterInput!

}

// MARK: ViewController output protocol

protocol ProfileViewOutput {
	func viewIsReady()
	func viewWillAppear()
}

extension ProfilePresenter: ProfileViewOutput {
	func viewIsReady() {
		view.setupInitialState()
		interactor.loadProfile()
	}
	
	func viewWillAppear() {
		interactor.loadProfile()
	}

}

// MARK: Interactor output protocol

protocol ProfileInteractorOutput: class {
	func didLoad(_ profile: Profile)
	func didFailLoad(_ error: Error)
	func didDeleteAvatar() -> Void
}

extension ProfilePresenter: ProfileInteractorOutput {
	func didDeleteAvatar() {
		interactor.loadProfile()
	}
	
	func didFailLoad(_ error: Error) {
		print("didFailLoad: ", error)
	}
	
	func didLoad(_ profile: Profile) {
		print("Profile: ",profile)
		view.profileView.props = ProfileView.Props(
			profile: profile,
			onEdit: Command { [weak self] in
				guard let self = self else { return }
				self.router.openEdit(profile, with: self.view)
			},
			onTapAvatar: Command { [weak self] in
				guard let self = self else { return }
				
				var actions = [
					Action(title: l10n(.chooseFromPhotoGallery), handler: { [weak self] in
						
					}),
					Action(title: l10n(.choosePresetAvatar), handler: { [weak self] in
						guard let self = self else { return }
						self.router.openAvatarPicker(with: self.view, onPick: Command { [weak self] in
							self?.interactor.loadProfile()
						})
					}),
					Action(title: l10n(.deleteAvatar), handler: { [weak self] in
						self?.interactor?.deleteAvatar()
					}, style: .destructive)
				]
				
				let cancelAction = Action(title: l10n(.cancel), style: .cancel)
				actions.append(cancelAction)
				self.view.showActionSheet(with: actions)
			}
		)
	}

}
