//
//  ProfileInteractor.swift
//  Profile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-18 08:16:13 +0000 lobster.kz. All rights reserved.
//

protocol ProfileInteractorInput {

}

// MARK: Implementation

class ProfileInteractor: ProfileInteractorInput {

	weak var output: ProfileInteractorOutput!

}
		