//
//  ProfileRouter.swift
//  Profile
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-18 08:16:13 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol ProfileRouterInput {

}

// MARK: Implementation

class ProfileRouter: ProfileRouterInput {

}
