//
//  GreetingViewController.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//

import UIKit

// MARK: View input protocol

protocol GreetingViewInput where Self: UIViewController {
	func setupInitialState()
	func renderRootview(with props: GreetingView.Props)
}

extension GreetingViewController: GreetingViewInput {

	func setupInitialState() {
		view.backgroundColor = .white
		view.addSubview(rootView)
		rootView.addConstraintsProgrammatically
		.pinToSuperSafeArea()
	}
	
	func renderRootview(with props: GreetingView.Props) {
		rootView.props = props
	}

}


class GreetingViewController: UIViewController {

	var output: GreetingViewOutput!
	let rootView = GreetingView()

	// MARK: Life cycle
	override func viewDidLoad() {
		super.viewDidLoad()
		output.viewIsReady()
	}

}

