//
//  VenueDescriptionRouter.swift
//  VenueDescription
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-27 16:23:49 +0000 lobster.kz. All rights reserved.
//

import UIKit
import SharedCodeFramework

protocol VenueDescriptionRouterInput {
	func presentComplaint(with vc: UIViewController, id: Int?, title: String?)
	func presentDetailInfo(with vc: UIViewController, venue: DoskazVenue)
	func addReview(with vc: UIViewController, venueId: Int, onReview: Command)
}

// MARK: Implementation

class VenueDescriptionRouter: VenueDescriptionRouterInput {
	func presentComplaint(with vc: UIViewController, id: Int?, title: String?) {
		let complaintViewController = ComplaintBuilder().assembleModule()
		complaintViewController.output.initWith(objectId: id, name: title)
		vc.presentEmbedded(complaintViewController)
	}
	
	func presentDetailInfo(with vc: UIViewController, venue: DoskazVenue) {
		let detailVC = DetailViewContoller()
		detailVC.venue = venue
		vc.presentEmbedded(detailVC)
	}
	
	func addReview(with vc: UIViewController, venueId: Int, onReview: Command) {
		let postReviewViewController = FeedbackViewController()
		postReviewViewController.initWith(objectId: venueId, onClose: onReview)
		vc.presentEmbedded(postReviewViewController)
	}
}
