//
//  VenueDescriptionPresenter.swift
//  VenueDescription
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-27 16:23:49 +0000 lobster.kz. All rights reserved.
//
import SharedCodeFramework
		
class VenueDescriptionPresenter {
	
	weak var view: VenueDescriptionViewInput!
	var interactor: VenueDescriptionInteractorInput!
	var router: VenueDescriptionRouterInput!

	var venue: DoskazVenue!
	var onReview: Command = .nop
	
	var lastSentStatus: Status!
}

// MARK: ViewController output protocol

protocol VenueDescriptionModuleInput {
	func render(doskazVenue: DoskazVenue, onReview: Command)
}

protocol VenueDescriptionViewOutput: VenueDescriptionModuleInput {
	func viewIsReady()
}

extension VenueDescriptionPresenter: VenueDescriptionViewOutput {
	func viewIsReady() {
		view.setupInitialState()
		guard let venue = venue else { return }
		let onTouchComplaint = Command { [weak self] in
			guard let self = self else { return }
		
			self.router.presentComplaint(
				with: self.view,
				id: self.venue?.id,
				title: self.venue.title
			)
		}
		
		let onTouchDetailInfo = Command { [weak self] in
			guard let self = self else { return }
			guard let venue = self.venue else { return }
			self.router.presentDetailInfo(with: self.view, venue: venue)
		}
		
		let onTouchVerify = Command { [weak self] in
			let actions = [
				Action(
					title: l10n(.no),
					handler: { [weak self] in
						guard let id = self?.venue.id else { return }
						self?.interactor.verifyVenue(with: id, status: Status.reject)
						self?.lastSentStatus = .reject
					},
					style: .destructive
				),
				Action(title: l10n(.yes), handler: { [weak self] in
					guard let id = self?.venue.id else { return }
					self?.interactor.verifyVenue(with: id, status: Status.confirm)
					self?.lastSentStatus = .confirm
				})
			]
			self?.view.showAlert(
				title: l10n(.verifyObjectData) + " \(venue.title)" ,
				message: l10n(.verifyObjectDataMessage),
				actions: actions
			)
		}
		
		view.rootView.props = VenueDescriptionView.Props(
			venue: venue,
			onTouchComplaint: onTouchComplaint,
			onTouchDetailInfo: onTouchDetailInfo,
			onTouchVerify: onTouchVerify
		)
	}
	
	func render(doskazVenue: DoskazVenue, onReview: Command) {
		self.onReview = onReview
		venue = doskazVenue
	}
	
	func showSecondAlert() {
		let actions = [
			Action(title: l10n(.yesHelp), handler: { [weak self] in
				guard let self = self, let id = self.venue.id else { return }
				self.router.addReview(with: self.view, venueId: id, onReview: self.onReview)
			}),
			Action(
				title: l10n(.cancel),
				handler: { [weak self] in
					self?.onReview.perform()
				},
				style: .cancel
			)
		]
		view.showAlert(title: l10n(.foundErrors), message: l10n(.foundErrorsMessage), actions: actions)
	}

}

// MARK: Interactor output protocol

protocol VenueDescriptionInteractorOutput: class {
	func didSucceedVerify() -> Void
	func didFailVerify(with error: Error) -> Void
}

extension VenueDescriptionPresenter: VenueDescriptionInteractorOutput {
	func didSucceedVerify() {
		switch lastSentStatus {
		case .reject:
			showSecondAlert()
		case .confirm:
			onReview.perform()
		case nil:
			break
		}
	}
	
	func didFailVerify(with error: Error) {
		print(error)
	}
	
}
