//
//  VenueDescriptionInteractor.swift
//  VenueDescription
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-27 16:23:49 +0000 lobster.kz. All rights reserved.
//

protocol VenueDescriptionInteractorInput {

}

// MARK: Implementation

class VenueDescriptionInteractor: VenueDescriptionInteractorInput {

	weak var output: VenueDescriptionInteractorOutput!

}
		