//
//  VenueDescriptionRouter.swift
//  VenueDescription
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-27 16:23:49 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol VenueDescriptionRouterInput {
	func presentComplaint(with vc: UIViewController)
}

// MARK: Implementation

class VenueDescriptionRouter: VenueDescriptionRouterInput {
	func presentComplaint(with vc: UIViewController) {
		let complaintViewController = ComplaintBuilder().assembleModule()
		vc.presentEmbedded(complaintViewController)
	}
}
