//
//  BlogRouter.swift
//  Blog
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-14 10:27:15 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol BlogRouterInput {

}

// MARK: Implementation

class BlogRouter: BlogRouterInput {

}
