//
//  BlogInteractor.swift
//  Blog
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-14 10:27:15 +0000 lobster.kz. All rights reserved.
//

protocol BlogInteractorInput {
	func loadBlog(with id: Int)
}

// MARK: Implementation

class BlogInteractor: BlogInteractorInput {

	weak var output: BlogInteractorOutput!
	
	func loadBlog(with id: Int) {
		APIBlogPost(onSuccess: { (blog) in
			print(blog)
		}, onFailure: { error in
			print(error)
		},
			 id: id
		)
		.dispatch()
		
	}

}
		