//
//  BlogRouter.swift
//  Blog
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-14 10:27:15 +0000 lobster.kz. All rights reserved.
//

import UIKit
import SharedCodeFramework

protocol BlogRouterInput {
	func showComments(with vc: UIViewController, comment: Comment, blogId: Int)
}

// MARK: Implementation

class BlogRouter: BlogRouterInput {
	func showComments(with vc: UIViewController, comment: Comment, blogId: Int) {
		let commentsvc = BlogCommentsViewController(
			blogComment: BlogComment.replies(blogId, comment),
			onPickComment: CommandWith<Comment> { [weak self] comment in
				self?.showComments(with: vc, comment: comment, blogId: blogId)
		})
		vc.navigationController?.pushViewController(commentsvc, animated: true)
	}
}
