//
//  BlogBuilder.swift
//  Blog
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-06-14 10:27:15 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct BlogBuilder {

	func assembleModule() -> BlogViewController {
		let viewController = BlogViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> BlogViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! BlogViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: BlogViewController) {

		let router = BlogRouter()

		let presenter = BlogPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = BlogInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
