//
//  GreetingRouter.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//

import UIKit

protocol GreetingRouterInput {

}

// MARK: Implementation

class GreetingRouter: GreetingRouterInput {

}
