//
//  GreetingPresenter.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//
		
class GreetingPresenter: GreetingModuleInput {
	
	weak var view: GreetingViewInput!
	var interactor: GreetingInteractorInput!
	var router: GreetingRouterInput!

}


// MARK: ViewController output protocol

protocol GreetingViewOutput {
	func viewIsReady()
}

extension GreetingPresenter: GreetingViewOutput {
	func viewIsReady() {
		view.setupInitialState()
	}

}


// MARK: Interactor output protocol

protocol GreetingInteractorOutput: class {

}

extension GreetingPresenter: GreetingInteractorOutput {

}

