//
//  GreetingInteractor.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//

protocol GreetingInteractorInput {

}

// MARK: Implementation

class GreetingInteractor: GreetingInteractorInput {

	weak var output: GreetingInteractorOutput!

}
		