//
//  GreetingPresenter.swift
//  Greeting
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-04-12 20:30:47 +0000 lobster.kz. All rights reserved.
//
import SharedCodeFramework
		
class GreetingPresenter {
	
	weak var view: GreetingViewInput!
	var interactor: GreetingInteractorInput!
	var router: GreetingRouterInput!

}

// MARK: ViewController output protocol

protocol GreetingViewOutput {
	func viewIsReady()
}

extension GreetingPresenter: GreetingViewOutput {
	func viewIsReady() {
		view.setupInitialState()
		view.renderRootview(with:
			GreetingView.Props(onPressNext: Command {
				self.router.presentCategories(with: self.view)
			})
		)
	}

}

// MARK: Interactor output protocol

protocol GreetingInteractorOutput: class {

}

extension GreetingPresenter: GreetingInteractorOutput {

}

