//
//  VenuePhotosBuilder.swift
//  VenuePhotos
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-27 10:33:42 +0000 lobster.kz. All rights reserved.
//

import UIKit

struct VenuePhotosBuilder {

	func assembleModule() -> VenuePhotosViewController {
		let viewController = VenuePhotosViewController()
		configure(viewController: viewController)
		return viewController
	}

	func assembleModule(with storyBoardName: String) -> VenuePhotosViewController {
		let storyboard = UIStoryboard(name: storyBoardName, bundle: .main)
		let viewController = storyboard.instantiateInitialViewController() as! VenuePhotosViewController
		configure(viewController: viewController)
		return viewController
	}

	private func configure(viewController: VenuePhotosViewController) {

		let router = VenuePhotosRouter()

		let presenter = VenuePhotosPresenter()
		presenter.view = viewController
		presenter.router = router

		let interactor = VenuePhotosInteractor()
		interactor.output = presenter

		presenter.interactor = interactor
		viewController.output = presenter
	}

}
