//
//  VenuePhotosPresenter.swift
//  VenuePhotos
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-27 10:33:42 +0000 lobster.kz. All rights reserved.
//
		
class VenuePhotosPresenter {
	
	weak var view: VenuePhotosViewInput!
	var interactor: VenuePhotosInteractorInput!
	var router: VenuePhotosRouterInput!

}

// MARK: ViewController output protocol

protocol VenuePhotosViewOutput {
	func viewIsReady()
}

extension VenuePhotosPresenter: VenuePhotosViewOutput {
	func viewIsReady() {
		view.setupInitialState()
	}

}

// MARK: Interactor output protocol

protocol VenuePhotosInteractorOutput: class {

}

extension VenuePhotosPresenter: VenuePhotosInteractorOutput {

}
