//
//  VenuePhotosInteractor.swift
//  VenuePhotos
//
//  Generated by ModuleGenerator.
//  Copyright © 2020-05-27 10:33:42 +0000 lobster.kz. All rights reserved.
//

protocol VenuePhotosInteractorInput {

}

// MARK: Implementation

class VenuePhotosInteractor: VenuePhotosInteractorInput {

	weak var output: VenuePhotosInteractorOutput!

}
		